#-*- coding: utf-8 -*-

{
	"name": "manajemen_surat Inherited",
	"version": "1.0", 
	"depends": [
		'base',
		'letter_management'
	],
	"author": "Akhmad D. Sembiring [vitraining.com]",
	"category": "Utility",
	"website": "http://vitraining.com",
	"images": ["static/description/images/main_screenshot.jpg"],
	"price": "10",
	"license": "OPL-1",
	"currency": "USD",
	"summary": "This is the manajemen_surat module generated by StarUML Odoo Generator Pro Version",
	"description": """

Information
======================================================================

* created menus
* created objects
* created views
* logics

""",
	"data": [
		# "view/surat_masuk.xml",
		# "view/surat_keluar.xml",
	],
	"installable": True,
	"auto_install": False,
	"application": True,
}